services:
  blogdb:
    image: postgres:17-alpine
    container_name: bloggerdb
    environment:
      POSTGRES_USER: bloggeruser
      POSTGRES_PASSWORD: skyconet
      POSTGRES_DB: bloggerdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: blog_redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: development
      POSTGRES_HOST: bloggerdb
      POSTGRES_PORT: 5432
      POSTGRES_USER: bloggeruser
      POSTGRES_PASSWORD: skyconet
      POSTGRES_DB: bloggerdb
    depends_on:
      - bloggerdb
    command: sh -c "./wait-for-db.sh && yarn migrate && yarn start"
    volumes:
      - ./docs:/app/docs

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      NODE_ENV: development
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
