swagger: '2.0'
info:
  title: Blog Platform API
  version: '1.0.0'
  description: Complete API documentation for the blog platform

paths:
  /api/posts:
    get:
      summary: Get all posts
      parameters:
        - name: page
          in: query
          type: integer
          description: Page number
        - name: limit
          in: query
          type: integer
          description: Items per page
      responses:
        200:
          description: List of posts
          schema:
            type: array
            items:
              $ref: '#/definitions/Post'